[package]
name = "lanplay-bench"
publish.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "lanplay-bench"
path = "src/main.rs"

[dependencies]
lanplay-capabilities = { workspace = true }
lanplay-protocol = { workspace = true }
lanplay-telemetry = { workspace = true }
lanplay-video-core = { workspace = true }
clap = { workspace = true }
