[package]
name = "lanplay-transport"
publish.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lanplay-protocol = { workspace = true }
lanplay-telemetry = { workspace = true }
lanplay-video-core = { workspace = true }
getrandom = { workspace = true }
hdrhistogram = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true }
